# Generated by Django 4.0.5 on 2023-05-18 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_code', models.CharField(max_length=12)),
                ('exp', models.CharField(max_length=12)),
                ('at', models.CharField(max_length=12)),
                ('attempt', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'users_auth_session',
            },
        ),
    ]
