version: '3'

services:
  db:
    image: postgres:14.2
    container_name: postgres
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
