version: '3'

services:
  db:
    image: postgres:14.2
    container_name: postgres
    env_file:
      - ./src/.env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/db-init.sh:/scripts/db-init.sh
      - ./db/sql:/sql
  
  cache_default:
    image: memcached:latest
    container_name: cache_default
    ports:
      - 11211:11211
  
  socket_db:
    image: redis:latest
    container_name: socket_db
    ports:
      - "6371:6379"
