# Generated by Django 4.0.5 on 2023-04-05 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, '저장됨'), (2, '임시'), (3, '만료'), (4, '삭제')], default=2)),
                ('display_id', models.UUIDField(db_index=True, default=uuid.UUID('790dc471-9fd1-4a0b-a979-d1720f4a56fd'), editable=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes_note',
            },
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='unique_note_name_author'),
        ),
    ]
