# Generated by Django 4.0.5 on 2023-04-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_keyword_alter_note_display_id_position_keyword_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['order']},
        ),
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_note_name_author',
        ),
        migrations.AlterField(
            model_name='keyword',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='notes.note'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['name', 'author'], name='notes_note_name_c92060_idx'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('name', 'author'), name='note_name_integrity'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('order', 'keyword'), name='keyword_position_order_integrity'),
        ),
        migrations.AlterModelTable(
            name='keyword',
            table='notes_keyword',
        ),
        migrations.AlterModelTable(
            name='position',
            table='notes_position',
        ),
    ]
