# Generated by Django 4.0.5 on 2023-04-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='keyword',
            name='order',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
