# Generated by Django 4.0.5 on 2023-04-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_keyword_keyword_order_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='order',
            field=models.IntegerField(),
        ),
    ]
