# Generated by Django 4.0.5 on 2023-04-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_alter_keyword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='text',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
