# Generated by Django 4.0.5 on 2023-04-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_keyword_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordChildren',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'notes_keyword_children',
            },
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='keyword',
            name='keyword_pos_id_integrity',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='pos_id',
        ),
        migrations.AddField(
            model_name='keyword',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.keyword'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='pos_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='pos_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='status',
            field=models.IntegerField(choices=[(1, 'UNSELECT'), (2, 'READ'), (3, 'EDIT')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='timestamp',
            field=models.CharField(default='1682710003432', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywordchildren',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='notes.keyword'),
        ),
        migrations.AddField(
            model_name='keywordchildren',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.keyword'),
        ),
    ]
