# Generated by Django 4.0.5 on 2023-04-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_keywordchildren_alter_keyword_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-pk']},
        ),
    ]
