# Generated by Django 4.0.5 on 2023-05-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='status',
            field=models.IntegerField(choices=[(1, 'UNSELECT'), (2, 'SELECT'), (3, 'EDIT')]),
        ),
    ]
