# Generated by Django 4.0.5 on 2023-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_keyword_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
